services:
    redis-1:
      image: redis
      ports:
        - "7002:7002"
      volumes:
        - ./config/redis-1.tmpl:/usr/local/etc/redis/redis.conf
      command: redis-server /usr/local/etc/redis/redis.conf
      networks:
        app_net:
          ipv4_address: 10.0.0.2
    redis-2:
      image: redis
      ports:
        - "7003:7003" 
      volumes:
        - ./config/redis-2.tmpl:/usr/local/etc/redis/redis.conf
      command: redis-server /usr/local/etc/redis/redis.conf
      networks:
        app_net:
          ipv4_address: 10.0.0.3
    redis-3:
      image: redis
      ports:
        - "7004:7004"
      volumes:
        - ./config/redis-3.tmpl:/usr/local/etc/redis/redis.conf
      command: redis-server /usr/local/etc/redis/redis.conf
      networks:
        app_net:
          ipv4_address: 10.0.0.4
    redis-4:
      image: redis
      ports:
        - "7005:7005"
      volumes:
        - ./config/redis-4.tmpl:/usr/local/etc/redis/redis.conf
      command: redis-server /usr/local/etc/redis/redis.conf
      networks:
        app_net:
          ipv4_address: 10.0.0.5
    redis-5:
      image: redis
      ports:
        - "7006:7006"
      volumes:
        - ./config/redis-5.tmpl:/usr/local/etc/redis/redis.conf
      command: redis-server /usr/local/etc/redis/redis.conf
      networks:
        app_net:
          ipv4_address: 10.0.0.6
    redis-6:
      image: redis
      ports:
        - "7007:7007"
      volumes:
        - ./config/redis-6.tmpl:/usr/local/etc/redis/redis.conf
      command: redis-server /usr/local/etc/redis/redis.conf
      networks:
        app_net:
          ipv4_address: 10.0.0.7

    redis-cluster:
        image: redis
        stdin_open: true # docker run -i
        tty: true        # docker run -t
#        command: redis-cli --cluster create 10.0.0.2:7002 10.0.0.3:7003 10.0.0.4:7004 10.0.0.5:7005 10.0.0.6:7006 10.0.0.7:7007 --cluster-replicas 1 --cluster-yes
#        command: redis-cli -p 7001 --cluster create 10.0.0.2:7002 10.0.0.3:7003 10.0.0.4:7004 10.0.0.5:7005 10.0.0.6:7006 10.0.0.7:7007 --cluster-replicas 1 --cluster-yes
        networks:
          app_net:
            ipv4_address: 10.0.0.10
        depends_on:
          - redis-1
          - redis-2
          - redis-3
          - redis-4
          - redis-5
          - redis-6

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/16
