all:
  hosts:
    node1:
      ansible_host: 192.168.0.34
      ip: 192.168.0.34
      access_ip: 192.168.0.34
    node2:
      ansible_host: 192.168.0.8
      ip: 192.168.0.8
      access_ip: 192.168.0.8
    node3:
      ansible_host: 192.168.0.11
      ip: 192.168.0.11
      access_ip: 192.168.0.11
    node4:
      ansible_host: 192.168.0.12
      ip: 192.168.0.12
      access_ip: 192.168.0.12
    cp1:
      ansible_host: 192.168.0.28
      ip: 192.168.0.28
      access_ip: 192.168.0.28
  children:
    kube_control_plane:
      hosts:
        cp1:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        cp1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
