apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-front
  namespace: prod
  labels:
    app: front
spec:
  selector:
    matchLabels:
      app: front
  replicas: 1
  template:
    metadata:
      labels:
        app: front
    spec:
     initContainers:
     containers:
      - image: egerpro/13frontend:0.0.1
        imagePullPolicy: IfNotPresent
        name: front
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env: 
        - name: BASE_URL
          value: http://back-svc:9000

---
apiVersion: v1
kind: Service
metadata:
  name: front-svc
  namespace: prod
  labels:
    app: front
spec:
  selector:
    app: front
  type: LoadBalancer
  ports:
  - name: front
    protocol: TCP
    port: 80
    targetPort: 80
